feature/#5 [회원 닉네임 변경 api 구현]
lucky-treee/diamond pull request #10
Opened 2023-02-18 08:52 UTC by jerry8534

회원 닉네임 변경 요청 시 실행되는 api 구현.

2023-02-18 11:35 UTC, SheepEatLion reviewed
1차 리뷰

2023-02-18 11:35 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
> +        this.nickname = newNickname;
newNickName 이라는 변수명은 필요 없어요 this. 키워드로 이미 구분이 됩니다. 
` String nickname ` 으로 변경해주세요~

2023-02-18 11:35 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
> +        this.nickname = newNickname;
추가로 로직 보니까 email 은 안쓰는데 왜받죠?

2023-02-18 11:35 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateNicknameService.java
> +        member.updateNickname(email, newNickname);
email 사용 안하고 있어요 여기에

2023-02-18 11:35 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateNicknameService.java
> +public class UpdateNicknameService implements MemberInfoUseCase {
리팩토링을 해야할 거 같은데 MemberInfoUseCase 클래스 자체의 이름을 MemberProfileUseCase 로 변경해주세요! 
이걸 바꾸면 따라서, 이걸 사용중인 다른 클래스에도 다 수정해줘야 할 거에요!

2023-02-18 11:35 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    @PostMapping("/updateNickname/{email}/{newNickname}")
url 에는 대문자가 들어가지 않습니다.
/update-nickname/  또는 update/nickname 으로 수정하는 게 좋아요.
개인적으론 후자를 추천

2023-02-21 14:55 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
> +        this.nickname = newNickname;
nickname으로 변경하고 email은 삭제했습니다~

2023-02-21 14:55 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateNicknameService.java
> +        member.updateNickname(email, newNickname);
수정했습니다.

2023-02-21 14:56 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateNicknameService.java
> +public class UpdateNicknameService implements MemberInfoUseCase {
다 바꿨습니다

2023-02-21 14:56 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    @PostMapping("/updateNickname/{email}/{newNickname}")
update/nickname으로 바꿨습니다

2023-02-22 11:33 UTC, SheepEatLion reviewed
리뷰

2023-02-22 12:05 UTC, turtlehopper requested changes

2023-02-22 12:05 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
>      @GetMapping("/get/{nickname}/{email}")
api verisoning에 맞는 URL path를 적용해 주세요. 
그리고 받아오는 파라미터 값이 두 개 이상이니,  @PathVariable이 아닌 @RequestParam으로 바꿔 주시면 됩니다.

2023-02-22 12:05 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    @PutMapping("/update/profile/{email}/{nickname}/{photo}")
@RequestParam을 적용하면 URL에 따로 파라미터를 명시하지 않아도 되는 것으로 압니다.  확인  부탁드려요.

2023-02-22 12:12 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
>          return new ResponseEntity<>(memberProfile, HttpStatus.OK);
api versioning에 맞게 URL Path 변경해주시고, 이 부분 또한 받아오는 파라미터 값이 두 개 이상이므로 @RequestParam으로 변경 해주세요.

2023-02-22 12:16 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
>      @GetMapping("/get/{nickname}/{email}")
api versioning에 맞게 URL Path를 변경해주세요.

2023-02-22 12:16 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
>      @GetMapping("/get/{nickname}/{email}")
그리고 받아오는 파라미터 값이 두 개 이상이므로, @RequestParam로 파라미터를 받아오는 방식으로 바꿔주세요.

2023-02-22 12:16 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    @PutMapping("/update/profile/{email}/{nickname}/{photo}")
여기도 api versioning에 맞게 URL Path 수정 해주세요.

2023-02-22 13:36 UTC, turtlehopper requested changes

2023-02-22 13:36 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +        return new ResultResponse<>(HttpStatus.OK);
ResultReponse가 아닌 ReponseEntity 클래스로 변경해 주세요.

2023-02-22 14:04 UTC, turtlehopper requested changes

2023-02-22 14:04 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateProfileService.java
> +    @Transactional
@Override 빠졌습니다.

2023-02-23 14:57 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/UpdateProfileAdapter.java
> +public class UpdateProfileAdapter implements UpdateProfilePort {
수정했습니다

2023-02-23 14:57 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/UpdateProfileAdapter.java
> +        MemberEntity memberEntity = memberRepository.findByEmail(email).orElseThrow(() -> new NotFoundException("해당 이메일이 존재하지 않습니다."));
수정했습니다

2023-02-23 14:58 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    @PutMapping("/update/profile/{email}/{nickname}/{photo}")
수정했습니다

2023-02-23 14:58 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
>      @GetMapping("/get/{nickname}/{email}")
수정했습니다

2023-02-23 14:59 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateProfileService.java
> +    @Transactional
수정했습니다

2023-02-23 15:00 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +        return new ResultResponse<>(HttpStatus.OK);
성공 여부만 보내주는건데 Entity로 보내야하는건가요?

2023-02-23 15:05 UTC, turtlehopper commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +        return new ResultResponse<>(HttpStatus.OK);
현재 ResultRespone 자체적으로 Custom으로 만들어진 객체 입니다. 프로젝트 진행을 하면서 spring framework에서 자체적으로 제공하는  ReponseEntity 클래스가 있어서 이 것을 사용해서 통일 하기로 했습니다.
제가 전달을 못 드렸나 보네요.

2023-02-25 14:10 UTC, SheepEatLion reviewed
리뷰3

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateMemberService.java
> +    public void updateMemberRequest(String email, String nickname, Photo photo) {
메소드명에 Request 는 필요 없을 거 같은데 어떤가여

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberProfileUseCase.java
> +    void updateMemberRequest(String email, String nickname, Photo photo);
여기 Request 도..!

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/UpdateMemberPort.java
> +    MemberProfile updateMember(String email, String nickname, Photo photo);
코드스타일 적용 안되었네요 줄바꿈이요

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    public ResponseEntity updateMember(@RequestParam("email") String email, @RequestParam("nickname") String nickname, @RequestParam("photo") Photo photo) {
requestParam 쓰면 url 에 변수명 포함되어야 하지 않나여

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateMemberService.java
> +        MemberEntity memberEntity = updateMemberPort.findByEmail(email);
이 줄 그냥 짜르고 어댑터에서 업데이트 치는 로직만 쓰는 걸로 수정하죠!

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/UpdateMemberAdapter.java
> +        return new MemberProfile(memberEntity);
리턴이 필요한 이유가 있나요?

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/UpdateMemberAdapter.java
> +        }
이거 얘기한대로 프론트엔드분들과 인터페이스 협의해서 null 로 들어올 일 없다는 상황으로 픽스 된다면 없애거나 컨트롤러단에서 Valid 적용하는 방향으로 바꾸는 게 좋아보여요

2023-02-25 14:10 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/domain/MemberProfile.java
> +    }
지금 구현한 update 로직을 그냥 플로우 그대로 따라가다보면, 이거 메소드 2개 안쓰고 있습니다.

2023-02-26 11:20 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateMemberService.java
> +    public void updateMemberRequest(String email, String nickname, Photo photo) {
삭제했습니다!

2023-02-26 11:20 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberProfileUseCase.java
> +    void updateMemberRequest(String email, String nickname, Photo photo);
삭제했습니다!

2023-02-26 11:20 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/UpdateMemberPort.java
> +    MemberProfile updateMember(String email, String nickname, Photo photo);
수정했습니다

2023-02-26 11:20 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
> +    public ResponseEntity updateMember(@RequestParam("email") String email, @RequestParam("nickname") String nickname, @RequestParam("photo") Photo photo) {
PathVariable이 url에 변수명 쓰는거 아닌가요...?

2023-02-26 11:20 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/application/service/UpdateMemberService.java
> +        MemberEntity memberEntity = updateMemberPort.findByEmail(email);
수정했습니다!

2023-02-26 11:21 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/UpdateMemberAdapter.java
> +        }
네 프런트 분들한테 물어보고 수정하겠습니다

2023-02-26 11:21 UTC, jerry8534 commented on member_service/src/main/java/com/luckytree/member_service/member/domain/MemberProfile.java
> +    }
삭제했습니다!

2023-02-27 13:57 UTC, SheepEatLion commented on member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberProfileUseCase.java
> +    void updateMemberRequest(String email, String nickname, Photo photo);
안달라졌는데....

2023-02-28 14:21 UTC, SheepEatLion approved these changes
ㄱㄱㄱㄱ

2023-02-28 14:22 UTC, turtlehopper approved these changes

2023-02-28 14:23 UTC, merged